# Generated by Django 3.1.3 on 2023-04-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_keycloak', '0008_auto_20230426_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidconnectprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
