# Generated by Django 4.2.9 on 2025-10-27 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_keycloak', '0009_auto_20230426_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidconnectprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oidc_profiles_user', to=settings.AUTH_USER_MODEL),
        ),
    ]