# Generated by Django 4.2.26 on 2026-05-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_keycloak', '0010_alter_openidconnectprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonce',
            name='next_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonce',
            name='redirect_uri',
            field=models.TextField(),
        ),
    ]
